# Generated by Django 4.0.5 on 2022-07-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_alter_datamodel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='wallet')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
